Implemented EventTypeEndpoint
bptlab/argos-backend pull request #37
Opened 2017-04-27 13:26 UTC by frederike-ramin

2017-04-27 13:29 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        // TODO where does the key for each event type come from? ("EventType{...}")
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO') Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS1135)

2017-04-27 13:29 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'

2017-04-27 13:49 UTC, Johannes-Schneider requested changes

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        List<EventType> eventTypes = PersistenceAdapterImpl.getInstance().getEventTypes();
Please log this request/response

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        JsonObject jsonEventTypes = getEventTypeJson(eventType);
Rename `jsonEventTypes` -> `jsonEventType`

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +
Log response please

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +                halt(HttpStatusCodes.ERROR, "no event type given in body");
Use `BAD_REQUEST` instead of `ERROR`, since this is not an internal server error, but an user error

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +                halt(HttpStatusCodes.ERROR, "event type name already in use, or failed to parse event type");
Use `BAD_REQUEST` instead of `ERROR`, since this is not an internal server error, but an user error

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +            logTrace(e);
Please use `LoggerUtilImpl.getInstance().error(...)` for a more consistent code-style

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +            halt(HttpStatusCodes.ERROR, "cannot find event type");
Use `BAD_REQUEST` instead of `ERROR`, since this is not an internal server error, but an user error

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +                if (!feedback) {
Please remove unnecessary variable `feedback` and do an inline check in the `if`-statement

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +                if (!feedback) {
Please do the check inline

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +                if (!feedback) {
Please do the check inline

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +                if (!feedback) {
Please do the check inline

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +                if (!feedback) {
Please do the check inline

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        return "";
Please log the response

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +            logTrace(e);
Please use `LoggerUtilImpl.getInstance().error(...)`

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +            halt(HttpStatusCodes.ERROR, e.getMessage());
Use `BAD_REQUEST` instead of `ERROR`, since this is not an internal server error, but an user error

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        return serializer.toJson(jsonTypeAttributes);
Please log the response

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +            logger.error("cannot parse request body to event queries '" + request.body() + "'");
Same as above mentioned

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +            logger.error("cannot parse request body to event entity mappings '" + request.body() + "'");
Same as above mentioned

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +            logger.error("cannot parse event type", e);
Please use `LoggerUtilImpl.getInstance().error(...)`

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        if (blockingEventTypeIds.size() == 0) {
Please use `List::isEmpty()`

2017-04-27 13:49 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        logger.trace("Reason: ", e);
Use `LoggerUtilImpl.getInstance()` instead

2017-04-27 14:47 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        if (blockingEventTypeIds.size() == 0) {
`blockingEventTypeIds` is not a List but a JsonArray, so this method is not applicable.

2017-04-27 14:53 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        // TODO where does the key for each event type come from? ("EventType{...}")
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO') Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS1135)

2017-04-28 07:31 UTC, Johannes-Schneider requested changes

2017-04-28 07:31 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        endpointUtil.logSendingResponse(logger, request, response.status(), "event types returned");
Please log the "real" response for better debugging, if needed

2017-04-28 07:31 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        endpointUtil.logSendingResponse(logger, request, response.status(), "event type queries returned");
Please log the real response

2017-04-28 07:31 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        endpointUtil.logSendingResponse(logger, request, response.status(), "event type entity mappings returned");
Please log the real response

2017-04-28 09:06 UTC, Johannes-Schneider approved these changes

2017-04-28 09:14 UTC, merged