Implement EntityTypeEndpointImpl
bptlab/argos-backend pull request #44
Opened 2017-05-03 12:12 UTC by frederike-ramin

2017-05-03 12:14 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Line has trailing spaces. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=checkstyle%3ARegexp_Singleline_BP2016)

2017-05-03 12:14 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +                if (!tree.containsKey(entityType.getParentId()))
![CRITICAL](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL') Missing curly brace. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS00121)

2017-05-03 12:14 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +    /**
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') First sentence should end with a period. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=checkstyle%3AJavadoc_Style_BP2016)

2017-05-03 12:14 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +    private void getChildJsons(List<EntityType> entityTypesOfLayer, Map<Integer, List<JsonObject>> layerMap, int layerId, Map<Long, List<EntityType>> tree) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Split this 157 characters long line (which is greater than 150 authorized). [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS00103)

2017-05-03 12:14 UTC, hpibptlab commented
SonarQube analysis reported 4 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-05-04 07:25 UTC, Johannes-Schneider requested changes

2017-05-04 07:25 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +            if (entityType.getParentId() == -1) {
This is actually not sufficent. There might be multiple `EventTypes` with `ParentId == -1`.

2017-05-04 12:07 UTC, Johannes-Schneider requested changes

2017-05-04 12:07 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +    private JsonObject jsonHierarchy;
Why would you save this as `JsonObject` and not as `String`?

2017-05-04 12:07 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +        if (typeAttributes == null) {
This will never happen.

2017-05-04 12:07 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +        if (allEntityTypes == null) {
This will never happen.

2017-05-04 12:22 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +import de.hpi.bpt.argos.util.HttpStatusCodes;
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Remove this unused import 'de.hpi.bpt.argos.util.HttpStatusCodes'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-05-04 12:22 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/entityType/EntityTypeEndpointImpl.java
> +
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Line has trailing spaces. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=checkstyle%3ARegexp_Singleline_BP2016)

2017-05-04 12:22 UTC, hpibptlab commented
SonarQube analysis reported 2 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-04 12:28 UTC, Johannes-Schneider approved these changes

2017-05-04 12:28 UTC, merged