Write tests for EventTypeEndpoint
bptlab/argos-backend pull request #46
Opened 2017-05-04 14:59 UTC by frederike-ramin

2017-05-04 15:01 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +                    if (!PersistenceAdapterImpl.getInstance().deleteArtifacts(conditions.toArray(conditionArray))) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Refactor this code to not nest more than 3 if/for/while/switch/try statements. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS134)

2017-05-04 15:01 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java
> +		// TODO: add more restEndpoints here
![INFO](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO') Complete the task associated to this TODO comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS1135)

2017-05-04 15:01 UTC, hpibptlab commented
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EventTypeEndpointImpl.java#L148](https://github.com/bptlab/argos-backend/blob/5974838ed7073b0a49564f41a51218dbbdc2389d/src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java#L148): The Cyclomatic Complexity of this method "deleteEventType" is 11 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MINOR][MINOR] [ArgosImpl.java](https://github.com/bptlab/argos-backend/blob/5974838ed7073b0a49564f41a51218dbbdc2389d/src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java): Add a new line at the end of this file. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS00113)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-04 15:22 UTC, hpibptlab commented
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EventTypeEndpointImpl.java#L148](https://github.com/bptlab/argos-backend/blob/47dd2bdd04b0276afe6048e636f470563e844b1b/src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java#L148): The Cyclomatic Complexity of this method "deleteEventType" is 11 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MINOR][MINOR] [ArgosImpl.java](https://github.com/bptlab/argos-backend/blob/47dd2bdd04b0276afe6048e636f470563e844b1b/src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java): Add a new line at the end of this file. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS00113)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-04 16:39 UTC, Johannes-Schneider requested changes

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/api/entity/EntityEndpointImpl.java
> +package de.hpi.bpt.argos.api.entity;
Please remove all double-linebreaks

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        JsonObject jsonEventTypes = new JsonObject();
Please remove this `JsonObject`, According to the rest-docu the `EventTypes-Array` is not wrapped within another object. So it is sufficent to only return the `Array`.

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        JsonObject jsonTypeAttributes = new JsonObject();
Same as with the `getEventTypes`

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        JsonObject jsonTypeQueries = new JsonObject();
Same as with the `getEventTypes`

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        JsonObject jsonEntityMappings = new JsonObject();
Same as with the `getEventTypes`

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        } catch (Exception e) {
Why would you catch the exception?

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java
> +package de.hpi.bpt.argos.core;
Did you change anything in here?

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +        } catch (Exception e) {
It's not necesarry to catch this exception, since the test will fail when any exception is thrown.

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +        JsonParser parser = new JsonParser();
Please use the `jsonParser` from `ArgosTestParent` to avoid additional objects.

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +    public void testGetEventType_InvalidEventTypeId() {
Please add the expected outcome to the method name.

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +    public void testCreateEventType() {
Please add webSocket tests.

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +        List<MappingCondition> conditions = ArgosTestUtil.createMappingConditions(mapping, true, new Pair<>((long) 1, (long) 2));
Please use `1L` and `2L` instead of cast.

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +            assertTrue(checkIfDeleted(existingAttribute, new ArrayList(attributes)));
Please add `<>` to `new ArrayList` to avoid unchecked assignments.

2017-05-04 16:39 UTC, Johannes-Schneider commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +                    fail("wrong attribute in json included");
Please use `assertTrue` to avoid nesting level.

2017-05-04 16:39 UTC, Hannes01071995 commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +                fail("not all json attributes exist");
Same as above.

2017-05-05 05:59 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/api/entity/EntityEndpointImpl.java
> +package de.hpi.bpt.argos.api.entity;
With me there are none.

2017-05-05 05:59 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +        JsonObject jsonEventTypes = new JsonObject();
It looked like it because of the name in front of the array. But alright, then I got it wrong.

2017-05-05 06:06 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java
> +package de.hpi.bpt.argos.core;
No, that happened when I rebased.

2017-05-05 06:08 UTC, frederike-ramin commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +    public void testGetEventType_InvalidEventTypeId() {
Just wanted to say, that I am protesting, but will do it anyways.

2017-05-05 06:18 UTC, hpibptlab commented
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EventTypeEndpointImpl.java#L146](https://github.com/bptlab/argos-backend/blob/0e47edc4d758c879d8748e2a5aad02fa6fb52f8d/src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java#L146): The Cyclomatic Complexity of this method "deleteEventType" is 11 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MINOR][MINOR] [ArgosImpl.java](https://github.com/bptlab/argos-backend/blob/0e47edc4d758c879d8748e2a5aad02fa6fb52f8d/src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java): Add a new line at the end of this file. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS00113)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-05 06:25 UTC, hpibptlab commented
SonarQube analysis reported 4 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 2 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EventTypeEndpointImpl.java#L146](https://github.com/bptlab/argos-backend/blob/18efe323ec31f070f828e3b3ebe9fb207b45b09d/src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java#L146): The Cyclomatic Complexity of this method "deleteEventType" is 11 which is greater than 10 authorized. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MINOR][MINOR] [ArgosImpl.java](https://github.com/bptlab/argos-backend/blob/18efe323ec31f070f828e3b3ebe9fb207b45b09d/src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java): Add a new line at the end of this file. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS00113)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-05 06:32 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +    private void deleteMappingConditions(List<EventEntityMapping> mappings) {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Missing a Javadoc comment. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=checkstyle%3AJavadocMethod_BP2016)

2017-05-05 06:32 UTC, hpibptlab commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [ArgosImpl.java](https://github.com/bptlab/argos-backend/blob/d14e46f92b5475d666d8f71f91d343587a1d0fb4/src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java): Add a new line at the end of this file. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS00113)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-05 07:37 UTC, Johannes-Schneider requested changes

2017-05-05 07:37 UTC, Hannes01071995 commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
>      @Test
Please add the expected result to the method name.

2017-05-05 07:37 UTC, Hannes01071995 commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +        assertFalse(foundAttributeJsons.size() != attributeArray.size());
Why double negation?

2017-05-05 07:37 UTC, Hannes01071995 commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +            if (!queryFound) {
Please use asserts instead of nested fails.

2017-05-05 07:37 UTC, Hannes01071995 commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> +            fail("not all json attributes exist");
Same here.

2017-05-05 07:45 UTC, hpibptlab commented
SonarQube analysis reported 2 issues
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [ArgosImpl.java](https://github.com/bptlab/argos-backend/blob/d75ec4236c2edff6946faa5559cfb765d2097506/src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java): Add a new line at the end of this file. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS00113)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-05 08:04 UTC, hpibptlab commented
SonarQube analysis reported 2 issues
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [ArgosImpl.java](https://github.com/bptlab/argos-backend/blob/f70fcabaf3e87ac637f8b1184f0165814d96a326/src/main/java/de/hpi/bpt/argos/core/ArgosImpl.java): Add a new line at the end of this file. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS00113)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-05 08:05 UTC, Johannes-Schneider approved these changes

2017-05-05 08:06 UTC, merged