Refactor request handling
bptlab/argos-backend pull request #52
Opened 2017-05-08 14:22 UTC by Hannes01071995

2017-05-08 14:28 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/api/eventType/EventTypeEndpointImpl.java
> +		if (!eventType.isDeletable()) {
![BLOCKER](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-blocker.png 'Severity: BLOCKER') NullPointerException might be thrown as 'eventType' is nullable here [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS2259)

2017-05-08 14:28 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![BLOCKER][BLOCKER] 1 blocker

Watch the comments in this conversation to review them.

[BLOCKER]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-blocker.png 'Severity: BLOCKER'

2017-05-08 14:30 UTC, frederike-ramin approved these changes
Nice refactoring!

2017-05-08 14:30 UTC, frederike-ramin commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> -        assertEquals(HttpStatusCodes.BAD_REQUEST, request.getResponseCode());
To me it's not a good idea to change this behavior. maybe just catch the parser exception and throw a halt?

2017-05-08 14:34 UTC, Hannes01071995 commented on src/test/java/de/hpi/bpt/argos/api/EventTypeEndpointTest.java
> -        assertEquals(HttpStatusCodes.BAD_REQUEST, request.getResponseCode());
I tried... But the code will lose its beauty when catching all the json NPEs.

2017-05-08 14:58 UTC, frederike-ramin requested changes

2017-05-08 14:58 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/util/RestEndpointUtilImpl.java
> -			throw e;
You don't want to rethrow that?

2017-05-08 15:11 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/util/RestEndpointUtilImpl.java
> -			throw e;
Actually no. This way I can handle all responses myself and dont have to hand them back to the framework. (This becomes important, when setting the response type in error-cases)

2017-05-09 07:04 UTC, frederike-ramin approved these changes

2017-05-09 08:19 UTC, merged