Bp 0502 status update event type
bptlab/argos-backend pull request #67
Opened 2017-05-23 11:47 UTC by Hannes01071995

2017-05-23 11:50 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/storage/dataModel/event/type/StatusUpdatedEventType.java
> +	/**
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') First sentence should end with a period. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=checkstyle%3AJavadoc_Style_BP2016)

2017-05-23 11:50 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/storage/dataModel/event/type/StatusUpdatedEventType.java
> +		EventCreationObserver customMapping = new EventCreationObserver() {
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Reduce this anonymous class number of lines from 23 to at most 20, or make it a named class. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS1188)
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Make this anonymous inner class a lambda [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS1604)

2017-05-23 11:50 UTC, hpibptlab commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 3 major

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-05-23 12:30 UTC, tommartensen approved these changes

2017-05-23 13:39 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/eventProcessing/creation/EventFactoryImpl.java
> +	private static final Gson serializer = new Gson();
![MAJOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR') Remove this unused "serializer" private field. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AS1068)

2017-05-23 13:39 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

2017-05-23 15:43 UTC, frederike-ramin requested changes
WIP

2017-05-23 15:43 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/api/eventQuery/EventQueryEndpointImpl.java
>  	private void checkEventTypeExists(EventQuery eventQuery) {
This does things additionally to its name. Maybe change that name accordingly?

2017-05-23 15:43 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/eventProcessing/creation/EventFactoryImpl.java
> +	@Override
Documentation

2017-05-23 15:43 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/eventProcessing/creation/EventFactoryImpl.java
> +		if (!feedback.isSuccessful()) {
Unicorn ca't be down as it just threw an event that triggered the status change.

2017-05-23 15:43 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/eventProcessing/creation/EventFactoryImpl.java
> +	private String finishEvent(String event, String eventTypeName) {
*finishXmlevent

2017-05-23 15:43 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/eventProcessing/status/EntityStatusCalculatorImpl.java
> +		if (processStatus.getUsedMapping().getTargetStatus() == null || processStatus.getUsedMapping().getTargetStatus().length() == 0) {
Maybe create a varialbe for targetStatus?

2017-05-23 15:43 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/storage/dataModel/entity/EntityImpl.java
> +			StatusUpdatedEventType.postEvent(this, this.status, status, statusChangeTrigger);
This is supposed to be th old status, but in fact is the new one.

2017-05-23 15:43 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/storage/dataModel/entity/VirtualRoot.java
> -	public void setStatus(String status) {
Why don't you leave that method?

2017-05-23 19:22 UTC, frederike-ramin requested changes

2017-05-23 19:22 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/storage/dataModel/event/type/StatusUpdatedEventType.java
> +				if (attribute.getTypeAttributeId() == typeAttribute.getId()) {
Isn't it possible that multiple attributes correspond to this special type attirbtue? Then you would return only the first one you find.

2017-05-23 19:22 UTC, frederike-ramin commented on src/main/java/de/hpi/bpt/argos/storage/dataModel/event/type/StatusUpdatedEventType.java
> +	private static long getAsLong(Attribute attribute) {
So it's actually getValueAsLong?

2017-05-23 19:22 UTC, frederike-ramin commented on src/test/java/de/hpi/bpt/argos/api/EntityTypeEndpointTest.java
> +        assertEquals(HttpStatusCodes.SUCCESS, request.getResponseCode());
Is that another thing that would be really ugly otherwise or why did you change that?

2017-05-23 19:22 UTC, frederike-ramin commented on src/test/java/de/hpi/bpt/argos/api/EventQueryEndpointTest.java
> +		assertEquals(HttpStatusCodes.FORBIDDEN, request.getResponseCode());
Maybe also check that no query is stored into database?

2017-05-24 06:20 UTC, Hannes01071995 commented on src/main/java/de/hpi/bpt/argos/storage/dataModel/event/type/StatusUpdatedEventType.java
> +				if (attribute.getTypeAttributeId() == typeAttribute.getId()) {
The assumption in this case is, that both the `TypeAttributes` and the `Attributes` belong to the same `Event`. Therefore, there must only be one `Attribute` which matches this condition.

2017-05-24 06:22 UTC, Hannes01071995 commented on src/test/java/de/hpi/bpt/argos/api/EntityTypeEndpointTest.java
> +        assertEquals(HttpStatusCodes.SUCCESS, request.getResponseCode());
In fact, I dont event know why the old version worked in first place...
All there is done is a database lookup, which will return an empty list at least. Therefore, the response code for this route will be always 200.

2017-05-24 06:57 UTC, frederike-ramin commented on src/test/java/de/hpi/bpt/argos/api/EntityTypeEndpointTest.java
> +        assertEquals(HttpStatusCodes.SUCCESS, request.getResponseCode());
Well, I guess it's okay, I'd prefer a BAD REQUEST though.

2017-05-24 07:18 UTC, frederike-ramin approved these changes

2017-05-24 07:20 UTC, hpibptlab commented on src/main/java/de/hpi/bpt/argos/eventProcessing/status/EntityStatusCalculatorImpl.java
>  import de.hpi.bpt.argos.storage.dataModel.mapping.EventEntityMapping;
![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR') Remove this unused import 'de.hpi.bpt.argos.storage.dataModel.mapping.EventEntityMapping'. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://bpt-lab.org/sonarqube/coding_rules#rule_key=squid%3AUselessImportCheck)

2017-05-24 07:20 UTC, hpibptlab commented
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

2017-05-24 07:38 UTC, merged